### PR TITLE
Move branding images to seed-rs.org repo

### PR DESCRIPTION
**Pull request by naufraghi**
- [x] point the image on the master once the https://github.com/seed-rs/seed-rs.org/pull/45 is merged

### CODE REVIEW

**Comment by MartinKavik** [comment]
Logo looks good, I'll merge it once "todolist" above is complete and it's rebased on current master.

**Comment by naufraghi** [comment]
The image was only in the readme @MartinKavik ?

**Comment by MartinKavik** [comment]
> The image was only in the readme

I think so.
Please rebase and I'll merge it.

**Comment by naufraghi** [comment]
@MartinKavik just rebased!

**Pull request merged**
