### PR TITLE
Improve CI speed

### PR DESCRIPTION
**Pull request by flosse**

### CODE REVIEW

**Review by fosskers — APPROVED** [review]

**Comment by flosse** [comment]
@fosskers can you merge it? I'm not allowed to do that.

**Comment by fosskers** [comment]
Sure. The failures are just the usual Clippy noise, which I see you're fixing in another PR :+1:

**Comment by fosskers** [comment]
Actually unfortunately I can't (even using commandline `git`), since the checks aren't passing and `master` is protected.

**Comment by MartinKavik** [comment]
I've added both of you as `seed-rs` org owners, I hope it'll resolve all permission problems :)

**Comment by fosskers** [comment]
Thank you @MartinKavik !

**Comment by flosse** [comment]
@MartinKavik thanks a lot!

**Pull request merged**
