### PR TITLE
Change type alias to struct

### PR DESCRIPTION
**Pull request by zakaluka**

### CODE REVIEW

**Comment by zakaluka** [comment]
Currently, `cargo make verify` fails because of an `implicit-clone`

```rust
    Checking gloo-events v0.1.1
    Checking gloo-timers v0.2.1
    Checking gloo-file v0.1.0
error: implicitly cloning a `Blob` by calling `to_owned` on its dereferenced type
  --> src\browser\web_socket\message.rs:51:51
   |
51 |             let blob = gloo_file::Blob::from(blob.to_owned());
   |                                                   ^^^^^^^^ help: consider using: `clone`
   |
   = note: `-D clippy::implicit-clone` implied by `-D clippy::pedantic`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#implicit_clone

error: aborting due to previous error

error: could not compile `seed`
```

**Comment by zakaluka** [comment]
This is for seed-rs/seed-quickstart#29

**Comment by MartinKavik** [comment]
Feel free to fix it according to the Clippy's suggestions :)

**Comment by zakaluka** [comment]
After I switched to the `stable` toolchain, the `clippy` error disappeared.  Hopefully this one is good to go.

**Pull request merged**
