### PR TITLE
Add `At::Role`

### PR DESCRIPTION
**Pull request by fosskers**
This PR adds a `Role` variant for the giant `At` enum, so that the `role` attribute can be used like so:

```html
<nav role="navigation"></nav>
```

### CODE REVIEW

**Comment by MartinKavik** [comment]
please run `cargo make verify` on your local machine

**Comment by fosskers** [comment]
Ah ok, I was just doing normal `cargo clippy`.

**Comment by MartinKavik** [comment]
It's written in `CONTRIBUTING.md`, but I'm not sure how much GitHub forces to read it by new contributors (if at all).

**Comment by fosskers** [comment]
I'm sure I read it when I first found seed, but since I haven't contributed directly to the project until now, I must have forgotten. Either way I'll fix this up today.

**Pull request merged**
